import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    shop: 'Shop',
    cart: 'Cart',
    orders: 'Orders',
    products: 'Products',
    sales: 'Sales',
    customers: 'Customers',
    purchases: 'Suppliers',
    payments: 'Payments',
    accounting: 'Accounting',
    'stock-alerts': 'Stock Alerts',
    'mobile-app': 'Mobile App',
    analytics: 'Analytics',
    reports: 'Reports',
    logout: 'Logout',
    survey: 'Survey',
    smartAssistantNav: 'Smart Assistant',
    govtSchemesNav: 'Government Schemes',
    customerView: 'Customer View',
    stockInProcurement: 'Purchases & Stock In',


    // Common
    search: 'Search',
    filter: 'Filter',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    noData: 'No data available',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    supplierLabel: 'Supplier',
    quantityLabel: 'Quantity',
    viewDetails: 'View Details',
    avgOrderValue: 'Avg Order Value',
    adjustSearchFilter: 'Try adjusting your search or filter criteria.',
    adminCannotBuy: 'Administrators cannot place retail orders. Use Purchases to restock.',
    statusLabel: 'Status',


    // Dashboard
    welcome: 'Welcome back',
    totalRevenue: 'Total Revenue',
    totalProducts: 'Total Products',
    totalCustomers: 'Total Customers',
    lowStockAlerts: 'Low Stock Alerts',
    creditReminders: 'Credit Reminders',
    recentTransactions: 'Recent Transactions',
    memberSince: 'Member since',
    myCart: 'My Cart',
    viewItems: 'View Items',
    trackHistory: 'Track History',
    support: 'Support',
    getHelp: 'Get Help',
    searchFertilizersPlaceholder: 'Search fertilizers, pesticides, compost...',
    allCategories: 'All Categories',
    productsCountLabel: 'products',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    reorder: 'Reorder',
    seasonalOffersLabel: 'Seasonal Offers',
    offersDescription: "Don't miss out on these limited-time deals!",
    validUntil: 'Valid until',
    quickActionsTitle: 'Quick Actions',
    trackOrder: 'Track Order',
    checkDeliveryStatus: 'Check delivery status',
    updateProfile: 'Update Profile',
    manageYourInformation: 'Manage your information',
    getNotifiedForFavorites: 'Get notified for favorites',
    farmerTipsLabel: 'Farmer Tips & Advice',
    allProducts: 'All Products',
    inStock: 'In Stock',
    limitedStock: 'Limited',
    noProductsFoundTitle: 'No products found',
    adjustSearchCategory: 'Try adjusting your search or category filter',
    lastUpdated: 'Last updated',
    projectedProfit: 'Projected Profit',
    efficiencyScore: 'Efficiency Score',
    basedOnMargin: 'Based on 22% avg margin',
    fromLastMonth: 'from last month',
    smartQuickActions: 'Smart Quick Actions',
    aiAssistant: 'AI Assistant',
    askFarmingQuestions: 'Ask farming questions',
    govtSchemes: 'Govt Schemes',
    checkEligiblePerks: 'Check eligible perks',
    soilHealth: 'Soil Health',
    viewCalculator: 'View calculator',
    monthlySales: 'Monthly Sales',
    productCategoriesLabel: 'Product Categories',
    noLowStockItems: 'No low stock items',
    due: 'Due',
    overdueLabel: 'Overdue',
    dueSoon: 'Due Soon',
    status: 'Status',
    completed: 'Completed',

    // Shop
    browseProducts: 'Browse and purchase quality fertilizers',
    addToCart: 'Add to Cart',
    outOfStock: 'Out of Stock',
    continueShopping: 'Continue Shopping',
    fertilizerShop: 'Fertilizer Shop',
    searchProducts: 'Search Products',
    searchByNameOrType: 'Search by name or type...',
    filterByType: 'Filter by Type',
    allTypes: 'All Types',
    stockCount: 'Stock: ',
    inCart: 'In Cart',
    noProductsAvailable: 'No products available',
    noProductsInStock: 'No products are currently in stock.',
    maxQuantityReached: 'Maximum quantity reached',
    removedFromCart: 'removed from cart',
    updatedQuantity: 'Updated quantity',
    cannotExceedStock: 'Cannot exceed available stock',
    adminViewNotice: 'ADMINISTRATOR RETAIL VIEW',
    adminViewNoticeDesc: 'Procure bulk stock via the "Stock In" module. This interface simulates the farmer\'s mobile experience for testing and monitoring.',
    premiumShop: 'Modern Fertilizer Hub',
    qualityInputs: 'Fueling your harvest with premium inputs',
    featuredDeals: 'Hot Deals for Farmers',
    specialOffer: 'Special Offer',
    off: 'OFF',
    lowStock: 'Low Stock',
    quickView: 'Quick View',
    noMatchFound: 'No Match Found',
    tryDifferentCategories: 'Try different categories or search terms',
    resetFilters: 'Reset Filters',


    // Cart
    shoppingCart: 'Shopping Cart',
    clearCart: 'Clear Cart',
    placeOrder: 'Place Order',
    orderSummary: 'Order Summary',
    shipping: 'Shipping',
    tax: 'Tax',
    total: 'Total',
    itemRemovedFromCart: 'Item removed from cart',
    cartCleared: 'Cart cleared',
    confirmClearCart: 'Are you sure you want to clear your cart?',
    orderPlacedSuccess: 'Order placed successfully!',
    orderNumberLabel: 'Order #',
    failedToPlaceOrder: 'Failed to place order. Please try again.',
    daysLeft: 'days left',
    unitCost: 'Unit Cost',
    returnToSupplier: 'Return to Supplier',
    dispose: 'Dispose',
    stockExpiryMgmt: 'Stock Expiry Management',
    generateReport: 'Generate Report',
    sendAlerts: 'Send Alerts',
    expiredProductsLabel: 'Expired Products',
    criticalProductsLabel: 'Critical (≤7 days)',
    atRiskValueLabel: 'Total Value at Risk',
    sortByDaysExpiry: 'Sort by Days to Expiry',
    sortByExpiryDate: 'Sort by Expiry Date',
    sortByTotalValue: 'Sort by Total Value',
    batchLabel: 'Batch',
    expiryGuidelines: 'Expiry Guidelines',
    notifications: 'Notifications',
    checkingForUpdates: 'Checking for updates...',
    lowStockAlert: 'Low Stock Alert',
    productExpiringSoon: 'Product Expiring Soon',
    overduePayment: 'Overdue Payment',
    allCaughtUp: 'All caught up!',
    noNewAlerts: 'No new alerts at this time.',
    refreshAlerts: 'Refresh Alerts',
    runningLow: 'is running low',
    remaining: 'remaining',
    overdueOf: 'has an overdue payment of',
    expiresOn: 'expires on',
    customer: 'Customer',
    items: 'Items',
    amount: 'Amount',
    date: 'Date',
    cartEmpty: 'Your cart is empty',
    addProductsToGetStarted: 'Add some products to get started',
    processing: 'Processing...',
    shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on Delivery',
    each: 'each',
    emptyCart: 'Your cart is empty',
    addSomethingSpecial: 'Add something special to your cart',
    discoverOurProducts: 'Discover our premium products',

    // Products
    fertilizerInventory: 'Fertilizer Inventory',
    manageProducts: 'Manage your agricultural products and supplies',
    addProduct: 'Add Product',
    productName: 'Product Name',
    type: 'Type',
    price: 'Price',
    stock: 'Stock',
    supplier: 'Supplier',
    description: 'Description',
    view: 'View',

    // Analytics (basic)
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisQuarter: 'This Quarter',
    thisYear: 'This Year',
    lastOrder: 'Last Order',

    // Customers
    customerManagement: 'Customer Management',
    addCustomer: 'Add Customer',
    searchCustomersPlaceholder: 'Search customers...',
    goodStanding: 'Good Standing',
    creditLimitLabel: 'Credit Limit',
    currentCreditLabel: 'Current Credit',
    dueDateLabel: 'Due Date',
    lastPurchaseLabel: 'Last Purchase',
    sendReminder: 'Send Reminder',
    viewHistory: 'View History',
    noCustomersFound: 'No customers found',

    // Accounting
    accountingAndGst: 'Accounting & GST',
    generateInvoice: 'Generate Invoice',
    totalGstLabel: 'Total GST',
    totalInvoicesLabel: 'Total Invoices',
    searchInvoicesPlaceholder: 'Search invoices...',
    recentInvoices: 'Recent Invoices',
    invoice: 'Invoice',
    gst: 'GST',
    download: 'Download',
    gstFeatures: 'GST Features',
    eInvoiceGen: 'e-Invoice Generation',
    eInvoiceGenDesc: 'Automatically generate e-invoices with QR codes',
    autoGstCalc: 'Auto GST Calculation',
    autoGstCalcDesc: 'Automatic GST calculation based on product categories',
    gstrReports: 'GSTR Reports',
    gstrReportsDesc: 'Generate GSTR-1 and GSTR-3B reports automatically',

    // Stock Expiry
    totalProductsLabel: 'Total Products',
    expiredLabel: 'Expired',
    criticalLabel: 'Critical',
    warningLabel: 'Warning',
    safeLabel: 'Safe',
    expiryLabel: 'Expiry',

    // Government Schemes
    govtSchemesTitle: 'Government Schemes & Subsidies',
    govtSchemesDesc: 'Access comprehensive information about agricultural schemes, subsidies, and government programs designed to support farmers and enhance agricultural productivity.',
    fetchingSchemes: 'Fetching the latest schemes for you...',
    eligibilityCriteria: 'Eligibility Criteria',
    keyBenefits: 'Key Benefits',
    howToApply: 'How to Apply',
    additionalResources: 'Additional Resources',
    minAgri: 'Ministry of Agriculture',
    deptFert: 'Department of Fertilizers',
    farmerPortalIndia: 'Farmer Portal India',
    visitPortal: 'Visit Portal',
    importantDisclaimer: 'Important Disclaimer',
    disclaimerText: 'Scheme details, eligibility criteria, and benefits are subject to periodic changes by the government. Users are strongly advised to verify information through local agricultural offices or the official portals listed above before making any financial decisions.',

    // Reports
    lowStockItems: 'Low Stock Items',
    salesReport: 'Sales Report',
    noSalesDataRange: 'No sales data available for the selected period.',
    inventoryReport: 'Inventory Report',
    noInventoryData: 'No inventory data available.',

    // Products (extended)
    manageInventoryDesc: 'Manage your agricultural products and supplies',
    filterSearch: 'Filter & Search',
    voiceSearch: 'Voice search',
    noProductsMatch: 'No products match your search',
    noProductsInventory: 'No products in inventory',
    startInventoryDesc: 'Start building your fertilizer inventory by adding your first product.',
    addFirstProduct: 'Add Your First Product',

    // Purchases
    purchaseManagement: 'Purchase Management',
    newPurchaseOrder: 'New Purchase Order',
    suppliers: 'Suppliers',
    purchaseOrders: 'Purchase Orders',
    searchSuppliersPlaceholder: 'Search suppliers...',
    searchOrdersPlaceholder: 'Search orders...',
    currentBalanceLabel: 'Current Balance',
    lastOrderLabel: 'Last Order',
    orderDateLabel: 'Order Date',
    deliveryDateLabel: 'Delivery Date',
    totalLabel: 'Total',
    orderItems: 'Order Items',
    trackDelivery: 'Track Delivery',

    // Order History
    orderHistory: 'Order History',
    noOrdersYet: 'No Orders Yet',
    noOrdersYetDesc: 'Your order history will appear here once you place your first order.',
    itemsOrderedLabel: 'Items Ordered',
    priceEach: '₹{price} each',
    orderHelp: 'Need help with this order?',
    contactSupport: 'Contact Support',

    // Sale Detail
    saleLabel: 'Sale',
    errorLoadingSale: 'Error loading sale',
    loadingSaleDetails: 'Loading sale details...',
    anonymous: 'Anonymous',
    productLabel: 'Product',
    itemsSoldLabel: 'Items Sold',
    pricePerUnitLabel: 'Price per Unit',
    noItemsFoundSale: 'No items found for this sale.',
    saleSummary: 'Sale Summary',

    // Smart Assistant
    smartFarmAssistant: 'Smart Farm Assistant',
    assistantWelcome: "Hello! I'm your Smart Farm Assistant. How can I help you today? You can ask me about weather, fertilizer recommendations, or crop health.",
    assistantUnavailable: 'Assistant is currently unavailable',
    assistantError: "I'm having trouble connecting right now. Please try again later.",
    clearChat: 'Clear Chat',
    aiFarmAssistant: 'AI Farm Assistant',
    mixingCompatibility: 'Mixing Compatibility',
    forecast: 'Forecast',
    sunnyConditions: 'Sunny Conditions',
    rain: 'Rain',
    farmProfile: 'Farm Profile',
    mainCropLabel: 'Main Crop',
    sizeLabel: 'Size',
    soilTypeLabel: 'Soil Type',
    aiInsights: 'AI Insights',
    farmAssistantAI: 'Farm Assistant AI',
    online: 'Online',
    speaking: 'Speaking...',
    queryPlaceholder: 'Type your agricultural query...',

    // Mobile App
    mobileAppIntegration: 'Mobile App Integration',
    downloadQR: 'Download QR',
    downloadApp: 'Download App',
    appTitle: 'Fertilizer Shop Mobile App',
    mobileAppDesc: 'Manage your business from anywhere with our powerful mobile application',
    availableOnIOSAndroid: 'Available on iOS & Android',
    realTimeSync: 'Real-time sync',
    totalDownloads: 'Total Downloads',
    activeUsers: 'Active Users',
    dailyTransactions: 'Daily Transactions',
    appRating: 'App Rating',
    mobileAppFeatures: 'Mobile App Features',
    recentMobileActivities: 'Recent Mobile Activities',
    downloadInstructions: 'Download Instructions',
    iosUsers: 'iOS Users',
    androidUsers: 'Android Users',

    // Analytics & Reports
    advancedAnalytics: 'Advanced Business Analytics',
    exportReport: 'Export Report',
    salesTrend: 'Sales Trend',
    profitTrend: 'Profit Trend',
    productPerformance: 'Product Performance',
    customerSegments: 'Customer Segments',
    topCustomers: 'Top Performing Customers',
    businessInsights: 'Strategic Business Insights',
    recommendations: 'AI Recommendations',
    totalProfit: 'Total Projected Profit',
    totalOrders: 'Total Orders',
    revenueGrowth: 'Revenue Growth',
    customerRetention: 'Customer Retention',
    inventoryAlert: 'Inventory Alert',
    increaseMarketing: 'Increase Marketing',
    customerEngagement: 'Customer Engagement',
    inventoryOptimization: 'Inventory Optimization',
    activeStatus: 'Active',
    totalSpent: 'Total Spent',

    // Survey
    helpImproveAgriFert: 'Help Us Improve AgriFert',
    surveyIntro: 'Your feedback is invaluable in helping us create the best fertilizer shop management system.',
    userExperience: 'User Experience',
    productFeatures: 'Product Features',
    shoppingFeatures: 'Shopping Features',
    additionalFeatures: 'Additional Features',
    ownerManagementFeatures: 'Owner/Management Features',
    overallSatisfaction: 'Overall Satisfaction',
    additionalFeedback: 'Additional Feedback',
    submitFeedback: 'Submit Feedback',
    thankYou: 'Thank You!',
    feedbackSubmittedSuccess: 'Your feedback has been submitted successfully.',
    qEaseOfUse: 'How easy is it to use the app?',
    qFeatureSatisfaction: 'How satisfied are you with the features?',
    qMobileExperience: 'How is your mobile experience?',
    qLikelyToRecommend: 'How likely are you to recommend us?',
    ratingExcellent: 'Excellent',
    ratingGood: 'Good',
    ratingAverage: 'Average',
    ratingPoor: 'Poor',
    ratingVeryPoor: 'Very Poor',


    // Add/Edit Product
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    productNameLabel: 'Product Name *',
    productNamePlaceholder: 'Enter product name',
    typeLabel: 'Type *',
    selectTypePlaceholder: 'Select type',
    priceLabel: 'Price (INR ₹) *',
    pricePlaceholder: '0.00',
    initialStockLabel: 'Initial Stock Quantity',
    currentStockLabel: 'Current Stock Quantity',
    quantityPlaceholder: '0',
    supplierPlaceholder: 'Enter supplier name',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Enter product description...',
    saveProduct: 'Save Product',
    updateProduct: 'Update Product',
    confirmDeleteProduct: 'Are you sure you want to delete this product?',
    errorDeletingProduct: 'Error deleting product',
    errorLoadingProduct: 'Error loading product',
    loadingProduct: 'Loading product...',

    // Sales
    addSale: 'Add Sale',
    backToSales: 'Back to Sales',
    customerInformation: 'Customer Information',
    customerNameLabel: 'Customer Name',
    phoneNumberLabel: 'Phone Number',
    saleItems: 'Sale Items',
    addItem: 'Add Item',
    selectProduct: 'Select product',
    pricePerUnit: 'Price per Unit',
    totalPrice: 'Total Price',
    totalAmountLabel: 'Total Amount',
    recording: 'Recording...',
    recordSale: 'Record Sale',
    noItemsAddedWarning: 'Please add at least one item to the sale',
    fillCorrectDetailsWarning: 'Please fill in all item details correctly',
    insufficientStockWarning: 'Insufficient stock for ',
    enterCustomerName: 'Enter customer name',
    enterPhoneNumber: 'Enter phone number',
    noItemsAddedMessage: 'No items added yet. Click "Add Item" to get started.',

    // Payments
    paymentManagement: 'Payment Management',
    recordPayment: 'Record Payment',
    totalRevenueLabel: 'Total Revenue',
    pendingPaymentsLabel: 'Pending Payments',
    totalTransactionsLabel: 'Total Transactions',
    searchPaymentsPlaceholder: 'Search payments...',
    allStatus: 'All Status',
    allMethods: 'All Methods',
    paymentMethodsTitle: 'Payment Methods',
    recentPayments: 'Recent Payments',
    method: 'Method',
    reference: 'Reference',
    actions: 'Actions',
    noPaymentsFound: 'No payments found',
    processingLabel: 'Processing',
    failedLabel: 'Failed',
    paymentFor: 'Payment for',
    saleIncome: 'Sale Income',
    purchaseExpense: 'Purchase Expense',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    netProfit: 'Net Balance',
    searchSales: 'Search Sales',
    searchSalesPlaceholder: 'Search by customer name, phone, or sale ID...',
    saleId: 'Sale ID',
    noSalesFound: 'No sales found',
    adjustSearchCriteria: 'Try adjusting your search criteria.',
    getStartedRecordingSale: 'Get started by recording your first sale.',
    manageSalesDesc: 'Track and manage your retail sales transactions',
    ordersFound: 'Orders Found',

    supplierAddedSuccess: 'Supplier added successfully',
    failedToAddSupplier: 'Failed to add supplier',
    orderCreatedSuccess: 'Order created successfully',
    failedToCreateOrder: 'Failed to create order',
    supplierName: 'Supplier Name',
    contactPerson: 'Contact Person',
    selectSupplier: 'Select Supplier',
    addItems: 'Add Items',
    itemName: 'Item Name',
    createOrder: 'Create Order',
    noSuppliersFound: 'No suppliers found',
    noOrdersFound: 'No purchase orders found',

    // Weather
    weatherInsights: 'Weather Insights',
    currentConditions: 'Current Conditions',
    soilMoisture: 'Soil Moisture',
    recommendation: 'Recommendation',
    dayForecast: '5-Day Forecast',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    farmingAdvice: 'Farming Advice',

    // Weather Widget
    yourFarmArea: 'Your Farm Area',
    partlyCloudy: 'Partly Cloudy',
    sunny: 'Sunny',
    rainy: 'Rainy',
    cloudy: 'Cloudy',
    goodConditionsFertilizer: 'Good conditions for fertilizer application. Soil moisture is optimal.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    day3: 'Day 3',
    day4: 'Day 4',
    day5: 'Day 5',
    failedToLoadWeatherData: 'Failed to load weather data',

    // Farmer Tips
    farmerTips: 'Farmer Tips & Advice',
    soilTesting: 'Soil Testing Importance',
    waterConservation: 'Water Conservation',
    pestManagement: 'Integrated Pest Management',

    // Disease Detection
    cropDiseaseDetection: 'Crop Disease Detection',
    uploadOrCapture: 'Upload or Capture Plant Image',
    takePhoto: 'Take Photo',
    uploadImage: 'Upload Image',
    analyzeForDiseases: 'Analyze for Diseases',
    analyzingImage: 'Analyzing image with AI...',
    analysisResult: 'Analysis Result',
    confidence: 'Confidence',
    diseaseDescription: 'Description',
    recommendedTreatment: 'Recommended Treatment',
    preventionTips: 'Prevention Tips',
    aiAnalysisNote: 'This is an AI-powered analysis. For accurate diagnosis, consult with agricultural experts or local extension services.',

    // Disease Names and Descriptions
    leafBlight: 'Leaf Blight',
    healthyPlant: 'Healthy Plant',
    powderyMildew: 'Powdery Mildew',
    leafBlightDesc: 'Fungal infection causing brown spots on leaves',
    healthyPlantDesc: 'No visible signs of disease detected',
    powderyMildewDesc: 'White powdery coating on leaves and stems',
    leafBlightTreatment: 'Apply copper-based fungicide and improve air circulation',
    healthyPlantTreatment: 'Continue current care practices',
    powderyMildewTreatment: 'Apply sulfur-based fungicide and reduce humidity',
    leafBlightPreventive: 'Ensure proper spacing between plants and avoid overhead watering',
    healthyPlantPreventive: 'Maintain regular monitoring and proper nutrition',
    powderyMildewPreventive: 'Improve air circulation and avoid wetting foliage',

    // Community Forum
    communityForum: 'Community Forum',
    newPost: 'New Post',
    shareFarmingExperience: 'Share your farming experience or ask for advice...',
    post: 'Post',
    searchDiscussions: 'Search discussions...',
    forumAllTopics: 'All Topics',
    cropDiscussion: 'Crop Discussion',
    pestProblems: 'Pest Problems',
    equipment: 'Equipment',
    marketPrices: 'Market Prices',
    forumFarmingAdvice: 'Farming Advice',
    noDiscussionsFound: 'No discussions found',
    forumAdjustSearchFilter: 'Try adjusting your search or filter criteria.',

    // Fertilizer Calculator
    fertilizerCalculator: 'Fertilizer Calculator',
    selectCropType: 'Select Crop Type',
    chooseCrop: 'Choose a crop...',
    landArea: 'Land Area',
    enterArea: 'Enter area',
    unit: 'Unit',
    acres: 'Acres',
    hectares: 'Hectares',
    soilType: 'Soil Type',
    chooseSoilType: 'Choose soil type...',
    sandySoil: 'Sandy Soil',
    loamySoil: 'Loamy Soil',
    claySoil: 'Clay Soil',
    siltSoil: 'Silt Soil',
    currentSoilNPKLevels: 'Current Soil NPK Levels (kg/ha) - Optional',
    calculateFertilizerRequirements: 'Calculate Fertilizer Requirements',
    fertilizerRecommendations: 'Fertilizer Recommendations',
    area: 'Area',
    requiredNPK: 'Required NPK',
    recommendedFertilizers: 'Recommended Fertilizers',
    bags: 'bags',
    calculateAgain: 'Calculate Again',
    calculatorNote: '💡 These recommendations are estimates. Soil testing and local agricultural expert advice is recommended for precise requirements.',

    // Education Hub
    farmerEducationHub: 'Farmer Education Hub',
    searchEducationalContent: 'Search educational content...',
    educationAllTopics: 'All Topics',
    soilManagement: 'Soil Management',
    irrigation: 'Irrigation',
    pestControl: 'Pest Control',
    organicFarming: 'Organic Farming',
    agriTech: 'Agri-Tech',
    farmBusiness: 'Farm Business',
    videos: 'Videos',
    articles: 'Articles',
    noContentFound: 'No content found',
    educationAdjustSearchFilter: 'Try adjusting your search or filter criteria.',

    // Landing Page
    trustedByFarmers: 'Trusted by 50,000+ Farmers',
    landingHeroTitle: 'Modern Solutions for',
    landingHeroSubtitle: 'Superior Farming',
    landingHeroDesc: 'Empowering farmers and shop owners with smart tools to manage inventory, sales, and crop health in one unified platform.',
    shopNow: 'Shop Now',
    getTheApp: 'Get Mobile App',
    login: 'Login',
    getStarted: 'Get Started',
    happyFarmers: 'Happy Farmers',
    productsAvailable: 'Products',
    ordersDelivered: 'Orders',
    satisfactionRate: 'Satisfaction',
    powerfulFeatures: 'Smart Tools for Better Yield',
    featureDesc: "Everything you need to maximize your farm's potential through advanced technology and expert guidance.",
    aiCropInsights: 'AI Assistant',
    aiDesc: 'Get personalized fertilizer recommendations and crop health diagnosis powered by advanced AI.',
    weatherForecast: 'Weather Alerts',
    weatherDesc: 'Real-time hyper-local weather alerts to help you plan your farm activities precisely.',
    voiceControl: 'Voice Guided',
    voiceDesc: 'Full control using voice commands in your local language. No typing required.',
    ctaTitle: 'Ready to Grow Your Harvest?',
    ctaDesc: 'Join thousands of farmers already using AgriFert to transform their agricultural practices and increase their income.',
    viewProducts: 'View Products',
    aboutUs: 'About',
    privacy: 'Privacy',
    terms: 'Terms',
    contact: 'Contact',
    allRightsReserved: 'All rights reserved.',

    // Language
    selectLanguage: 'Select Language',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  },
  hi: {
    // Navigation
    dashboard: 'डैशबोर्ड',
    shop: 'दुकान',
    cart: 'कार्ट',
    orders: 'ऑर्डर',
    products: 'उत्पाद',
    sales: 'बिक्री',
    customers: 'किसान',
    purchases: 'आपूर्तिकर्ता',
    payments: 'भुगतान',
    accounting: 'लेखांकन',
    'stock-alerts': 'स्टॉक अलर्ट',
    'mobile-app': 'मोबाइल ऐप',
    analytics: 'विश्लेषण',
    reports: 'रिपोर्ट',
    logout: 'लॉगआउट',
    farmers: 'किसान',
    survey: 'सर्वेक्षण',
    smartAssistantNav: 'स्मार्ट सहायक',
    govtSchemesNav: 'सरकारी योजनाएं',
    customerView: 'ग्राहक दृश्य',
    stockInProcurement: 'खरीद और स्टॉक इन',


    // Common
    search: 'खोजें',
    filter: 'फिल्टर',
    add: 'जोड़ें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    confirm: 'पुष्टि करें',
    yes: 'हाँ',
    no: 'नहीं',

    // Dashboard
    welcome: 'वापसी पर स्वागत है',
    totalRevenue: 'कुल राजस्व',
    totalProducts: 'कुल उत्पाद',
    totalCustomers: 'कुल किसान',
    avgOrderValue: 'औसत ऑर्डर मूल्य',
    lowStockAlerts: 'कम स्टॉक अलर्ट',
    creditReminders: 'क्रेडिट रिमाइंडर',
    recentTransactions: 'हाल की लेनदेन',

    // Analytics & Reports
    advancedAnalytics: 'उन्नत व्यापार विश्लेषण',
    exportReport: 'रिपोर्ट निर्यात करें',
    salesTrend: 'बिक्री का रुझान',
    profitTrend: 'लाभ का रुझान',
    productPerformance: 'उत्पाद प्रदर्शन',
    customerSegments: 'ग्राहक वर्ग',
    topCustomers: 'शीर्ष प्रदर्शन करने वाले ग्राहक',
    businessInsights: 'रणनीतिक व्यापार अंतर्दृष्टि',
    recommendations: 'एआई सिफारिशें',
    totalProfit: 'कुल अनुमानित लाभ',
    totalOrders: 'कुल ऑर्डर',
    revenueGrowth: 'राजस्व वृद्धि',
    customerRetention: 'ग्राहक प्रतिधारण',
    inventoryAlert: 'इन्वेंटरी अलर्ट',
    increaseMarketing: 'मार्केटिंग बढ़ाएं',
    customerEngagement: 'ग्राहक जुड़ाव',
    inventoryOptimization: 'इन्वेंटरी अनुकूलन',
    activeStatus: 'सक्रिय',
    totalSpent: 'कुल खर्च',
    totalIncome: 'कुल आय',
    totalExpense: 'कुल खर्च',
    netProfit: 'कुल शेष',
    saleIncome: 'बिक्री आय',
    purchaseExpense: 'खरीद खर्च',

    // Shop
    browseProducts: 'गुणवत्तापूर्ण उर्वरकों को ब्राउज़ और खरीदें',
    addToCart: 'कार्ट में जोड़ें',
    outOfStock: 'स्टॉक ख़त्म',
    continueShopping: 'खरीदारी जारी रखें',

    // Cart
    shoppingCart: 'शॉपिंग कार्ट',
    clearCart: 'कार्ट खाली करें',
    placeOrder: 'ऑर्डर दें',
    orderSummary: 'ऑर्डर सारांश',
    shipping: 'शिपिंग',
    tax: 'कर',
    total: 'कुल',

    // Products
    fertilizerInventory: 'उर्वरक इन्वेंटरी',
    manageProducts: 'अपने कृषि उत्पादों और आपूर्ति का प्रबंधन करें',
    addProduct: 'उत्पाद जोड़ें',
    productName: 'उत्पाद का नाम',
    type: 'प्रकार',
    price: 'मूल्य',
    stock: 'स्टॉक',
    supplier: 'आपूर्तिकर्ता',
    description: 'विवरण',

    // Weather
    weatherInsights: 'मौसम अंतर्दृष्टि',
    currentConditions: 'वर्तमान स्थितियाँ',
    soilMoisture: 'मिट्टी की नमी',
    recommendation: 'सिफारिश',
    dayForecast: '5-दिन का पूर्वानुमान',
    humidity: 'नमी',
    windSpeed: 'हवा की गति',
    farmingAdvice: 'खेती की सलाह',

    // Weather Widget
    yourFarmArea: 'आपका खेत क्षेत्र',
    partlyCloudy: 'आंशिक बादल',
    sunny: 'धूप',
    rainy: 'बारिश',
    cloudy: 'बादल',
    goodConditionsFertilizer: 'उर्वरक लगाने के लिए अच्छी स्थितियां। मिट्टी की नमी इष्टतम है।',
    today: 'आज',
    tomorrow: 'कल',
    day3: 'दिन 3',
    day4: 'दिन 4',
    day5: 'दिन 5',
    failedToLoadWeatherData: 'मौसम डेटा लोड करने में विफल',
    daysLeft: 'दिन शेष',
    unitCost: 'इकाई लागत',
    returnToSupplier: 'आपूर्तिकर्ता को लौटाएं',
    dispose: 'निस्तारण करें',
    stockExpiryMgmt: 'स्टॉक समाप्ति प्रबंधन',
    generateReport: 'रिपोर्ट तैयार करें',
    sendAlerts: 'अलर्ट भेजें',
    expiredProductsLabel: 'समाप्त उत्पाद',
    criticalProductsLabel: 'गंभीर (≤7 दिन)',
    atRiskValueLabel: 'जोखिम में कुल मूल्य',
    sortByDaysExpiry: 'समाप्ति के दिनों के अनुसार क्रमबद्ध करें',
    sortByExpiryDate: 'समाप्ति तिथि के अनुसार क्रमबद्ध करें',
    sortByTotalValue: 'कुल मूल्य के अनुसार क्रमबद्ध करें',
    batchLabel: 'बैच',
    expiryGuidelines: 'समाप्ति दिशानिर्देश',
    notifications: 'सूचनाएं',
    checkingForUpdates: 'अपडेट की जांच की जा रही है...',
    lowStockAlert: 'कम स्टॉक अलर्ट',
    productExpiringSoon: 'उत्पाद जल्द ही समाप्त होने वाला है',
    overduePayment: 'देय भुगतान',
    allCaughtUp: 'सब कुछ ठीक है!',
    noNewAlerts: 'इस समय कोई नई चेतावनी नहीं है।',
    refreshAlerts: 'अलर्ट रिफ्रेश करें',
    runningLow: 'कम चल रहा है',
    remaining: 'शेष',
    overdueOf: 'का देय भुगतान है',
    expiresOn: 'को समाप्त हो रहा है',
    memberSince: 'सदस्यता शुरू',
    myCart: 'मेरा कार्ट',
    viewItems: 'आइटम देखें',
    trackHistory: 'इतिहास ट्रैक करें',
    support: 'सहायता',
    getHelp: 'मदद लें',
    searchFertilizersPlaceholder: 'उर्वरक, कीटनाशक खोजें...',
    allCategories: 'सभी श्रेणियां',
    productsCountLabel: 'उत्पाद',
    recentOrders: 'हाल के आदेश',
    viewAll: 'सभी देखें',
    reorder: 'पुन: ऑर्डर करें',
    seasonalOffersLabel: 'मौसमी ऑफर',
    offersDescription: 'इस रोपण सीजन के लिए विशेष छूट',
    validUntil: 'तक वैध',
    farmerTipsLabel: 'किसान टिप्स और सलाह',
    quickActionsTitle: 'त्वरित कार्रवाई',
    trackOrder: 'ऑर्डर ट्रैक करें',
    checkDeliveryStatus: 'डिलीवरी स्थिति जांचें',
    updateProfile: 'प्रोफ़ाइल अपडेट करें',
    manageYourInformation: 'अपनी जानकारी प्रबंधित करें',
    getNotifiedForFavorites: 'पसंदीदा के लिए सूचना प्राप्त करें',
    allProducts: 'सभी उत्पाद',
    noProductsFoundTitle: 'कोई उत्पाद नहीं मिला',
    adjustSearchCategory: 'अपनी खोज या श्रेणी को समायोजित करने का प्रयास करें',
    lastUpdated: 'अंतिम अपडेट',
    projectedProfit: 'अनुमानित लाभ',
    basedOnMargin: '22% मार्जिन पर आधारित',
    efficiencyScore: 'दक्षता स्कोर',
    fromLastMonth: 'पिछले महीने से',
    smartQuickActions: 'स्मार्ट त्वरित कार्रवाई',
    askFarmingQuestions: 'खेती के प्रश्न पूछें',
    govtSchemes: 'सरकारी योजनाएं',
    checkEligiblePerks: 'पात्र लाभ जांचें',
    soilHealth: 'मिट्टी का स्वास्थ्य',
    viewCalculator: 'कैलकुलेटर देखें',
    monthlySales: 'मासिक बिक्री',
    productCategoriesLabel: 'उत्पाद श्रेणियां',
    noLowStockItems: 'वर्तमान में कोई भी आइटम स्टॉक में कम नहीं है',
    due: 'देय',
    overdueLabel: 'अतिदेय',
    dueSoon: 'जल्द ही देय',
    customer: 'ग्राहक',
    items: 'आइटम',
    amount: 'राशि',
    date: 'तारीख',
    status: 'स्थिति',
    completed: 'पूरा हुआ',

    // Farmer Tips
    farmerTips: 'किसान टिप्स और सलाह',
    soilTesting: 'मिट्टी परीक्षण की महत्व',
    waterConservation: 'जल संरक्षण',
    pestManagement: 'एकीकृत कीट प्रबंधन',

    // Disease Names and Descriptions
    leafBlight: 'पत्ती का झुलसा',
    healthyPlant: 'स्वस्थ पौधा',
    powderyMildew: 'पाउडरी मिल्ड्यू',
    leafBlightDesc: 'पत्तियों पर भूरे धब्बे पैदा करने वाला फंगल संक्रमण',
    healthyPlantDesc: 'कोई रोग के लक्षण नहीं दिखाई दिए',
    powderyMildewDesc: 'पत्तियों और तनों पर सफेद पाउडरी की परत',
    leafBlightTreatment: 'कॉपर-आधारित फफूंदनाशक लगाएं और हवा के संचार में सुधार करें',
    healthyPlantTreatment: 'वर्तमान देखभाल प्रथाओं को जारी रखें',
    powderyMildewTreatment: 'सल्फर-आधारित फफूंदनाशक लगाएं और नमी कम करें',
    leafBlightPreventive: 'पौधों के बीच उचित दूरी सुनिश्चित करें और ऊपर से पानी देने से बचें',
    healthyPlantPreventive: 'नियमित निगरानी और उचित पोषण बनाए रखें',
    powderyMildewPreventive: 'हवा के संचार में सुधार करें और पत्तियों को गीला करने से बचें',

    // Fertilizer Calculator
    fertilizerCalculator: 'उर्वरक कैलकुलेटर',
    selectCropType: 'फसल प्रकार चुनें',
    chooseCrop: 'एक फसल चुनें...',
    landArea: 'भूमि क्षेत्र',
    enterArea: 'क्षेत्र दर्ज करें',
    unit: 'इकाई',
    acres: 'एकड़',
    hectares: 'हेक्टेयर',
    soilType: 'मिट्टी का प्रकार',
    chooseSoilType: 'मिट्टी का प्रकार चुनें...',
    sandySoil: 'रेतीली मिट्टी',
    loamySoil: 'दोमट मिट्टी',
    claySoil: 'चिकनी मिट्टी',
    siltSoil: 'गाद मिट्टी',
    currentSoilNPKLevels: 'वर्तमान मिट्टी NPK स्तर (kg/ha) - वैकल्पिक',
    calculateFertilizerRequirements: 'उर्वरक आवश्यकताएं गणना करें',
    fertilizerRecommendations: 'उर्वरक सिफारिशें',
    area: 'क्षेत्र',
    requiredNPK: 'आवश्यक NPK',
    recommendedFertilizers: 'अनुशंसित उर्वरक',
    bags: 'बोरे',
    calculateAgain: 'फिर से गणना करें',
    calculatorNote: '💡 ये सिफारिशें अनुमान हैं। सटीक आवश्यकताओं के लिए मिट्टी परीक्षण और स्थानीय कृषि विशेषज्ञ की सलाह की सिफारिश की जाती है।',

    // Education Hub
    farmerEducationHub: 'किसान शिक्षा केंद्र',
    searchEducationalContent: 'शैक्षिक सामग्री खोजें...',
    educationAllTopics: 'सभी विषय',
    soilManagement: 'मिट्टी प्रबंधन',
    irrigation: 'सिंचाई',
    pestControl: 'कीट नियंत्रण',
    organicFarming: 'जैविक खेती',
    agriTech: 'कृषि-टेक',
    farmBusiness: 'खेती व्यवसाय',
    videos: 'वीडियो',
    articles: 'लेख',
    noContentFound: 'कोई सामग्री नहीं मिली',
    educationAdjustSearchFilter: 'अपनी खोज या फ़िल्टर मानदंड समायोजित करने का प्रयास करें।',

    // Community Forum
    communityForum: 'सामुदायिक मंच',
    newPost: 'नई पोस्ट',
    shareFarmingExperience: 'अपना कृषि अनुभव साझा करें या सलाह मांगें...',
    post: 'पोस्ट करें',
    searchDiscussions: 'चर्चाओं में खोजें...',
    forumAllTopics: 'सभी विषय',
    cropDiscussion: 'फसल चर्चा',
    pestProblems: 'कीट समस्याएं',
    equipment: 'उपकरण',
    marketPrices: 'बाजार मूल्य',
    forumFarmingAdvice: 'कृषि सलाह',
    noDiscussionsFound: 'कोई चर्चा नहीं मिली',
    forumAdjustSearchFilter: 'अपनी खोज या फ़िल्टर मानदंड समायोजित करने का प्रयास करें।',

    // Sale Detail
    saleLabel: 'बिक्री',
    itemsSoldLabel: 'बेचे गए आइटम',
    pricePerUnitLabel: 'प्रति इकाई मूल्य',
    noItemsFoundSale: 'इस बिक्री के लिए कोई आइटम नहीं मिला।',

    // Language
    selectLanguage: 'भाषा चुनें',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  },
  te: {
    // Telugu translations would go here
    dashboard: 'డ్యాష్‌బోర్డ్',
    shop: 'షాప్',
    cart: 'కార్ట్',
    orders: 'ఆర్డర్‌లు',
    products: 'ఉత్పత్తులు',
    sales: 'అమ్మకాలు',
    customers: 'రైతులు',
    purchases: 'సప్లైయర్‌లు',
    payments: 'చెల్లింపులు',
    accounting: 'లెక్కింగ్',
    'stock-alerts': 'స్టాక్ అలర్ట్‌లు',
    'mobile-app': 'మొబైల్ యాప్',
    analytics: 'విశ్లేషణ',
    reports: 'రిపోర్ట్‌లు',
    logout: 'లాగ్‌అవుట్',
    farmers: 'రైతులు',
    survey: 'సర్వే',
    smartAssistantNav: 'స్మార్ట్ అసిస్టెంట్',
    govtSchemesNav: 'ప్రభుత్వ పథకాలు',
    customerView: 'కస్టమర్ వ్యూ',
    stockInProcurement: 'కొనుగోళ్లు & స్టాక్ ఇన్',
    adminViewNotice: 'అడ్మినిస్ట్రేటర్ రిటైల్ వ్యూ',
    adminViewNoticeDesc: 'స్టాక్ ఇన్ మాడ్యూల్ ద్వారా బల్క్ స్టాక్‌ను సేకరించండి. ఈ ఇంటర్‌ఫేస్ టెస్టింగ్ కోసం రైతు మొబైల్ అనుభవాన్ని అనుకరిస్తుంది.',
    premiumShop: 'ఆధునిక ఎరువుల కేంద్రం',
    qualityInputs: 'ప్రీమియం ఇన్పుట్లతో మీ పంటకు శక్తినివ్వండి',
    featuredDeals: 'రైతుల కోసం హాట్ డీల్స్',
    emptyCart: 'మీ కార్ట్ ఖాళీగా ఉంది',
    addSomethingSpecial: 'మీ కార్ట్‌కు ఏదైనా ప్రత్యేకమైనది జోడించండి',
    discoverOurProducts: 'మా ప్రీమియం ఉత్పత్తులను కనుగొనండి',
    ordersFound: 'ఆర్డర్లు కనుగొనబడ్డాయి',
    manageSalesDesc: 'మీ రిటైల్ అమ్మకాల లావాదేవీలను ట్రాక్ చేయండి మరియు నిర్వహించండి',
    addSupplier: 'సరఫరాదారుని జోడించు',
    supplierName: 'సరఫరాదారు పేరు',
    contactPerson: 'సంప్రదింపు వ్యక్తి',
    selectSupplier: 'సరఫరాదారుని ఎంచుకోండి',
    addItems: 'వస్తువులను జోడించు',
    itemName: 'వస్తువు పేరు',
    createOrder: 'ఆర్డర్ సృష్టించు',
    noSuppliersFound: 'సరఫరాదారులు కనుగొనబడలేదు',
    noOrdersFound: 'కొనుగోలు ఆర్డర్లు కనుగొనబడలేదు',
    deliveryDate: 'డెలివరీ తేదీ',
    statusLabel: 'స్థితి',


    welcome: 'తిరిగి స్వాగతం',
    totalRevenue: 'మొత్తం ఆదాయం',
    totalProducts: 'మొత్తం ఉత్పత్తులు',
    totalCustomers: 'మొత్తం రైతులు',
    avgOrderValue: 'సగటు ఆర్డర్ విలువ',
    browseProducts: 'నాణ్యమైన ఎరువులను బ్రౌజ్ చేసి కొనండి',
    addToCart: 'కార్ట్‌కు జోడించు',
    outOfStock: 'స్టాక్ లేదు',
    continueShopping: 'షాపింగ్ కొనసాగించు',

    shoppingCart: 'షాపింగ్ కార్ట్',
    clearCart: 'కార్ట్ ఖాళీ చేయి',
    placeOrder: 'ఆర్డర్ చేయి',
    orderSummary: 'ఆర్డర్ సారాంశం',
    shipping: 'షిప్పింగ్',
    tax: 'పన్ను',
    total: 'మొత్తం',

    fertilizerInventory: 'ఎరువుల ఇన్వెంటరీ',
    manageProducts: 'మీ వ్యవసాయ ఉత్పత్తులు మరియు సరఫరాలను నిర్వహించండి',
    addProduct: 'ఉత్పత్తి జోడించు',
    productName: 'ఉత్పత్తి పేరు',
    type: 'రకం',
    price: 'ధర',
    stock: 'స్టాక్',
    supplier: 'సప్లైయర్',
    description: 'వివరణ',

    weatherInsights: 'వాతావరణ అంతర్దృష్టులు',
    currentConditions: 'ప్రస్తుత పరిస్థితులు',
    soilMoisture: 'మట్టి తేమ',
    recommendation: 'సిఫార్సు',
    dayForecast: '5-రోజుల పూర్వాభిప్రాయం',
    humidity: 'తేమ',
    windSpeed: 'గాలి వేగం',
    farmingAdvice: 'వ్యవసాయ సలహా',

    // Weather Widget
    yourFarmArea: 'మీ పొలం ప్రాంతం',
    partlyCloudy: 'పాక్షిక మేఘాలు',
    sunny: 'వెలుతురు',
    rainy: 'వర్షం',
    cloudy: 'మేఘాలు',
    goodConditionsFertilizer: 'ఎరువులను వర్తించడానికి మంచి పరిస్థితులు. మట్టి తేమ అనుకూలంగా ఉంది.',
    today: 'ఈరోజు',
    tomorrow: 'రేపు',
    day3: 'రోజు 3',
    day4: 'రోజు 4',
    day5: 'రోజు 5',
    failedToLoadWeatherData: 'వాతావరణ డేటాను లోడ్ చేయడంలో విఫలమైంది',
    daysLeft: 'రోజులు మిగిలి ఉన్నాయి',
    unitCost: 'యూనిట్ ఖర్చు',
    returnToSupplier: 'సరఫరాదారుకు తిరిగి ఇవ్వండి',
    dispose: 'పారవేయండి',
    stockExpiryMgmt: 'స్టాక్ గడువు నిర్వహణ',
    generateReport: 'నివేదికను రూపొందించండి',
    sendAlerts: 'అలర్ట్‌లు పంపండి',
    expiredProductsLabel: 'గడువు ముగిసిన ఉత్పత్తులు',
    criticalProductsLabel: 'క్లిష్టమైన స్థితి (≤7 రోజులు)',
    atRiskValueLabel: 'ప్రమాదంలో ఉన్న మొత్తం విలువ',
    sortByDaysExpiry: 'గడువు ముగిసే రోజుల ప్రకారం క్రమబద్ధీకరించండి',
    sortByExpiryDate: 'గడువు ముగింపు తేదీ ప్రకారం క్రమబద్ధీకరించండి',
    sortByTotalValue: 'మొత్తం విలువ ప్రకారం క్రమబద్ధీకరించండి',
    batchLabel: 'బ్యాచ్',
    expiryGuidelines: 'గడువు ముగింపు మార్గదర్శకాలు',
    notifications: 'నోటిఫికేషన్‌లు',
    checkingForUpdates: 'అప్‌డేట్‌ల కోసం తనిఖీ చేస్తోంది...',
    lowStockAlert: 'తక్కువ స్టాక్ అలర్ట్',
    productExpiringSoon: 'ఉత్పత్తి త్వరలో గడువు ముగుస్తుంది',
    overduePayment: 'గడువు ముగిసిన చెల్లింపు',
    allCaughtUp: 'అంతా అప్‌డేట్ అయింది!',
    noNewAlerts: 'ప్రస్తుతానికి కొత్త అలర్ట్‌లు లేవు.',
    refreshAlerts: 'అలర్ట్‌లను రిఫ్రెష్ చేయండి',
    runningLow: 'తక్కువగా ఉంది',
    remaining: 'మిగిలి ఉంది',
    overdueOf: 'గడువు ముగిసిన చెల్లింపు ఉంది',
    expiresOn: 'న గడువు ముగుస్తుంది',

    farmerTips: 'రైతు సలహాలు మరియు చిట్కాలు',
    soilTesting: 'మట్టి పరీక్ష ముఖ్యత్వం',
    waterConservation: 'నీటి సంరక్షణ',
    pestManagement: 'సమగ్ర పురుగుల నిర్వహణ',

    // Disease Names and Descriptions
    leafBlight: 'ఆకు బ్లైట్',
    healthyPlant: 'ఆరోగ్యకరమైన మొక్క',
    powderyMildew: 'పౌడరీ మిల్డ్యూ',
    leafBlightDesc: 'ఆకులపై బ్రౌన్ స్పాట్‌లను కలిగించే ఫంగల్ ఇన్ఫెక్షన్',
    healthyPlantDesc: 'వ్యాధి లక్షణాలు కనిపించలేదు',
    powderyMildewDesc: 'ఆకుల మరియు కాండాలపై తెలుపు పౌడరీ కోటింగ్',
    leafBlightTreatment: 'కాపర్-ఆధారిత ఫంగిసైడ్ వర్తించండి మరియు గాలి ప్రవాహాన్ని మెరుగుపరచండి',
    healthyPlantTreatment: 'ప్రస్తుత సంరక్షణ పద్ధతులను కొనసాగించండి',
    powderyMildewTreatment: 'సల్ఫర్-ఆధారిత ఫంగిసైడ్ వర్తించండి మరియు తేమను తగ్గించండి',
    leafBlightPreventive: 'మొక్కల మధ్య సరైన దూరం నిర్ధారించండి మరియు పై నుండి నీరు పోసేలను నివారించండి',
    healthyPlantPreventive: 'సాధారణ పర్యవేక్షణ మరియు సరైన పోషణను నిర్వహించండి',
    powderyMildewPreventive: 'గాలి ప్రవాహాన్ని మెరుగుపరచండి మరియు ఆకులను తడిపించేలను నివారించండి',

    // Fertilizer Calculator
    fertilizerCalculator: 'ఎరువుల క్యాల్క్యులేటర్',
    selectCropType: 'పంట రకం ఎంచుకోండి',
    chooseCrop: 'పంటను ఎంచుకోండి...',
    landArea: 'భూభాగం',
    enterArea: 'ప్రాంతాన్ని నమోదు చేయండి',
    unit: 'యూనిట్',
    acres: 'ఎకరాలు',
    hectares: 'హెక్టార్లు',
    soilType: 'మట్టి రకం',
    chooseSoilType: 'మట్టి రకం ఎంచుకోండి...',
    sandySoil: 'ఇసుక మట్టి',
    loamySoil: 'లోమీ మట్టి',
    claySoil: 'మట్టి మట్టి',
    siltSoil: 'సిల్ట్ మట్టి',
    currentSoilNPKLevels: 'ప్రస్తుత మట్టి NPK స్థాయిలు (kg/ha) - ఐచ్ఛికం',
    calculateFertilizerRequirements: 'ఎరువుల అవసరాలను లెక్కించండి',
    fertilizerRecommendations: 'ఎరువుల సిఫార్సులు',
    area: 'ప్రాంతం',
    requiredNPK: 'అవసరమైన NPK',
    recommendedFertilizers: 'సిఫార్సు చేయబడిన ఎరువులు',
    bags: 'పొట్లు',
    calculateAgain: 'మళ్లీ లెక్కించు',
    calculatorNote: '💡 ఈ సిఫార్సులు అంచనాలు. ఖచ్చితమైన అవసరాల కోసం మట్టి పరీక్ష మరియు స్థానిక వ్యవసాయ నిపుణుల సలహా సిఫార్సు చేయబడింది.',

    // Education Hub
    farmerEducationHub: 'రైతు విద్యా కేంద్రం',
    searchEducationalContent: 'విద్యా సామగ్రిని వెతకండి...',
    educationAllTopics: 'అన్ని అంశాలు',
    soilManagement: 'మట్టి నిర్వహణ',
    irrigation: 'నీటిపారుదల',
    pestControl: 'పురుగుల నియంత్రణ',
    organicFarming: 'సేంద్రీయ వ్యవసాయం',
    agriTech: 'వ్యవసాయ-టెక్',
    farmBusiness: 'వ్యవసాయ వ్యాపారం',
    videos: 'వీడియోలు',
    articles: 'లేఖలు',
    noContentFound: 'సామగ్రి కనుగొనబడలేదు',
    educationAdjustSearchFilter: 'మీ శోధన లేదా ఫిల్టర్ ప్రమాణాలను సర్దుబాటు చేయడానికి ప్రయత్నించండి.',

    // Community Forum
    communityForum: 'సమాజ ఫోరమ్',
    newPost: 'కొత్త పోస్ట్',
    shareFarmingExperience: 'మీ వ్యవసాయ అనుభవాన్ని పంచుకోండి లేదా సలహా అడగండి...',
    post: 'పోస్ట్ చేయండి',
    searchDiscussions: 'చర్చలలో వెతకండి...',
    forumAllTopics: 'అన్ని అంశాలు',
    cropDiscussion: 'పంట చర్చ',
    pestProblems: 'పురుగుల సమస్యలు',
    equipment: 'పరికరాలు',
    marketPrices: 'మార్కెట్ ధరలు',
    forumFarmingAdvice: 'వ్యవసాయ సలహా',
    noDiscussionsFound: 'చర్చలు కనుగొనబడలేదు',
    forumAdjustSearchFilter: 'మీ శోధన లేదా ఫిల్టర్ ప్రమాణాలను సర్దుబాటు చేయడానికి ప్రయత్నించండి.',

    selectLanguage: 'భాష ఎంచుకోండి',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  },
  ta: {
    // Navigation
    dashboard: 'டாஷ்போர்டு',
    shop: 'ஷாப்',
    cart: 'கார்ட்',
    orders: 'ஆர்டர்கள்',
    products: 'தயாரிப்புகள்',
    sales: 'விற்பனை',
    customers: 'விவசாயிகள்',
    purchases: 'சப்ளையர்கள்',
    payments: 'பணம் செலுத்துதல்',
    accounting: 'கணக்கியல்',
    'stock-alerts': 'இருப்பு எச்சரிக்கைகள்',
    'mobile-app': 'மொபைல் ஆப்',
    analytics: 'பகுப்பாய்வு',
    reports: 'அறிக்கைகள்',
    logout: 'வெளியேறு',
    farmers: 'விவசாயிகள்',
    survey: 'கணக்கெடுப்பு',
    smartAssistantNav: 'ஸ்மார்ட் உதவியாளர்',
    govtSchemesNav: 'அரசு திட்டங்கள்',

    // Common
    search: 'தேடு',
    filter: 'வடிகட்டு',
    add: 'சேர்',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    loading: 'ஏற்றப்படுகிறது...',
    noData: 'தரவு இல்லை',
    confirm: 'உறுதிப்படுத்து',
    yes: 'ஆம்',
    no: 'இல்லை',

    // Dashboard
    welcome: 'மீண்டும் வருக',
    totalRevenue: 'மொத்த வருவாய்',
    totalProducts: 'மொத்த தயாரிப்புகள்',
    totalCustomers: 'மொத்த விவசாயிகள்',
    avgOrderValue: 'சராசரி ஆர்டர் மதிப்பு',
    lowStockAlerts: 'குறைந்த இருப்பு எச்சரிக்கைகள்',
    creditReminders: 'கடன் நினைவூட்டல்கள்',
    recentTransactions: 'சமீபத்திய பரிமாற்றங்கள்',

    // Shop
    browseProducts: 'தரமான உரங்களை உலாவவும் மற்றும் வாங்கவும்',
    addToCart: 'கார்ட்டில் சேர்',
    outOfStock: 'இருப்பு இல்லை',
    continueShopping: 'ஷாப்பிங்கைத் தொடரவும்',

    // Cart
    shoppingCart: 'ஷாப்பிங் கார்ட்',
    clearCart: 'கார்ட்டை காலி செய்',
    placeOrder: 'ஆர்டர் செய்',
    orderSummary: 'ஆர்டர் சுருக்கம்',
    shipping: 'ஷிப்பிங்',
    tax: 'வரி',
    total: 'மொத்தம்',

    // Products
    fertilizerInventory: 'உர இருப்பு',
    manageProducts: 'உங்கள் விவசாய தயாரிப்புகள் மற்றும் விநியோகங்களை நிர்வகிக்கவும்',
    addProduct: 'தயாரிப்பை சேர்',
    productName: 'தயாரிப்பு பெயர்',
    type: 'வகை',
    price: 'விலை',
    stock: 'இருப்பு',
    supplier: 'சப்ளையர்',
    description: 'விளக்கம்',

    // Weather
    weatherInsights: 'வானிலை நுண்ணறிவு',
    currentConditions: 'தற்போதைய நிலை',
    soilMoisture: 'மண் ஈரப்பதம்',
    recommendation: 'பரிந்துரை',
    dayForecast: '5-நாள் முன்னறிவிப்பு',
    humidity: 'ஈரப்பதம்',
    windSpeed: 'காற்றின் வேகம்',
    farmingAdvice: 'விவசாய ஆலோசனை',

    // Weather Widget
    yourFarmArea: 'உங்கள் பண்ணை பகுதி',
    partlyCloudy: 'ஓரளவு மேகமூட்டம்',
    sunny: 'வெயில்',
    rainy: 'மழை',
    cloudy: 'மேகமூட்டம்',
    goodConditionsFertilizer: 'உரம் போட நல்ல நிலை. மண் ஈரப்பதம் சிறப்பாக உள்ளது.',
    today: 'இன்று',
    tomorrow: 'நாளை',
    day3: 'நாள் 3',
    day4: 'நாள் 4',
    day5: 'நாள் 5',
    failedToLoadWeatherData: 'வானிலை தரவை ஏற்ற முடியவில்லை',

    // Farmer Tips
    farmerTips: 'விவசாய குறிப்புகள் மற்றும் ஆலோசனைகள்',
    soilTesting: 'மண் பரிசோதனையின் முக்கியத்துவம்',
    waterConservation: 'நீர் பாதுகாப்பு',
    pestManagement: 'ஒருங்கிணைந்த பூச்சி மேலாண்மை',

    // Disease Names and Descriptions
    leafBlight: 'இலை கருகல்',
    healthyPlant: 'ஆரோக்கியமான செடி',
    powderyMildew: 'சாம்பல் நோய்',
    leafBlightDesc: 'இலைகளில் பழுப்பு நிற புள்ளிகளை ஏற்படுத்தும் பூஞ்சை தொற்று',
    healthyPlantDesc: 'நோய் அறிகுறிகள் எதுவும் காணப்படவில்லை',
    powderyMildewDesc: 'இலைகள் மற்றும் தண்டுகளில் வெள்ளை மாவு போன்ற பூச்சு',
    leafBlightTreatment: 'தாமிரம் சார்ந்த பூஞ்சைக் கொல்லியைப் பயன்படுத்தவும் மற்றும் காற்றோட்டத்தை மேம்படுத்தவும்',
    healthyPlantTreatment: 'தற்போதைய பராமரிப்பு முறைகளைத் தொடரவும்',
    powderyMildewTreatment: 'கந்தகம் சார்ந்த பூஞ்சைக் கொல்லியைப் பயன்படுத்தவும் மற்றும் ஈரப்பதத்தைக் குறைக்கவும்',
    leafBlightPreventive: 'செடிகளுக்கு இடையில் முறையான இடைவெளியை உறுதிப்படுத்தவும் மற்றும் மேலிருந்து நீர் ஊற்றுவதைத் தவிர்க்கவும்',
    healthyPlantPreventive: 'வழக்கமான கண்காணிப்பு மற்றும் முறையான ஊட்டச்சத்தை பராமரிக்கவும்',
    powderyMildewPreventive: 'காற்றோட்டத்தை மேம்படுத்தவும் மற்றும் இலைகளை நனைப்பதைத் தவிர்க்கவும்',

    // Fertilizer Calculator
    fertilizerCalculator: 'உர கால்குலேட்டர்',
    selectCropType: 'பயிர் வகையைத் தேர்ந்தெடுக்கவும்',
    chooseCrop: 'ஒரு பயிரைத் தேர்ந்தெடுக்கவும்...',
    landArea: 'நிலப்பரப்பு',
    enterArea: 'பரப்பளவை உள்ளிடவும்',
    unit: 'அலகு',
    acres: 'ஏக்கர்',
    hectares: 'ஹெக்டேர்',
    soilType: 'மண் வகை',
    chooseSoilType: 'மண் வகையைத் தேர்ந்தெடுக்கவும்...',
    sandySoil: 'மணல் மண்',
    loamySoil: 'வண்டல் மண்',
    claySoil: 'களிமண்',
    siltSoil: 'வண்டல் மண்',
    currentSoilNPKLevels: 'தற்போதைய மண் NPK அளவுகள் (kg/ha) - விருப்பமானது',
    calculateFertilizerRequirements: 'உரத் தேவைகளைக் கணக்கிடுங்கள்',
    fertilizerRecommendations: 'உரப் பரிந்துரைகள்',
    area: 'பரப்பளவு',
    requiredNPK: 'தேவையான NPK',
    recommendedFertilizers: 'பரிந்துரைக்கப்பட்ட உரங்கள்',
    bags: 'மூட்டைகள்',
    calculateAgain: 'மீண்டும் கணக்கிடு',
    calculatorNote: '💡 இந்தப் பரிந்துரைகள் தோராயமானவை. துல்லியமான தேவைகளுக்கு மண் பரிசோதனை மற்றும் உள்ளூர் விவசாய நிபுணர் ஆலோசனையை பரிந்துரைக்கிறோம்.',

    // Education Hub
    farmerEducationHub: 'விவசாய கல்வி மையம்',
    searchEducationalContent: 'கல்வி உள்ளடக்கத்தைத் தேடுங்கள்...',
    educationAllTopics: 'அனைத்து தலைப்புகளும்',
    soilManagement: 'மண் மேலாண்மை',
    irrigation: 'நீர்ப்பாசனம்',
    pestControl: 'பூச்சி கட்டுப்பாடு',
    organicFarming: 'இயற்கை விவசாயம்',
    agriTech: 'அக்ரி-டெக்',
    farmBusiness: 'பண்ணை வணிகம்',
    videos: 'வீடியோக்கள்',
    articles: 'கட்டுரைகள்',
    noContentFound: 'உள்ளடக்கம் எதுவும் இல்லை',
    educationAdjustSearchFilter: 'உங்கள் தேடல் அல்லது வடிகட்டி அளவுகோல்களை மாற்ற முயற்சிக்கவும்.',

    // Community Forum
    communityForum: 'சமூக மன்றம்',
    newPost: 'புதிய பதிவு',
    shareFarmingExperience: 'உங்கள் விவசாய அனுபவத்தைப் பகிரவும் அல்லது ஆலோசனை கேட்கவும்...',
    post: 'பதிவிடு',
    searchDiscussions: 'விவாதங்களைத் தேடுங்கள்...',
    forumAllTopics: 'அனைத்து தலைப்புகளும்',
    cropDiscussion: 'பயிர் விவாதம்',
    pestProblems: 'பூச்சி சிக்கல்கள்',
    equipment: 'கருவிகள்',
    marketPrices: 'சந்தை விலைகள்',
    forumFarmingAdvice: 'விவசாய ஆலோசனை',
    noDiscussionsFound: 'விவாதங்கள் எதுவும் இல்லை',
    forumAdjustSearchFilter: 'உங்கள் தேடல் அல்லது வடிகட்டி அளவுகோல்களை மாற்ற முயற்சிக்கவும்.',

    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  },
  kn: {
    // Navigation
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    shop: 'ಅಂಗಡಿ',
    cart: 'ಕಾರ್ಟ್',
    orders: 'ಆದೇಶಗಳು',
    products: 'ಉತ್ಪನ್ನಗಳು',
    sales: 'ಮಾರಾಟ',
    customers: 'ರೈತರು',
    purchases: 'ಪೂರೈಕೆದಾರರು',
    payments: 'ಪಾವತಿಗಳು',
    accounting: 'ಲೆಕ್ಕಪತ್ರ',
    'stock-alerts': 'ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆಗಳು',
    'mobile-app': 'ಮೊಬೈಲ್ ಆಪ್',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    reports: 'ವರದಿಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    farmers: 'ರೈತರು',
    survey: 'ಸಮೀಕ್ಷೆ',
    smartAssistantNav: 'ಸ್ಮಾರ್ಟ್ ಅಸಿಸ್ಟೆಂಟ್',
    govtSchemesNav: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',

    // Common
    search: 'ಹುಡುಕಿ',
    filter: 'ಫಿಲ್ಟರ್',
    add: 'ಸೇರಿಸಿ',
    edit: 'ತಿದ್ದುಪಡಿ',
    delete: 'ಅಳಿಸಿ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಗೊಳಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    noData: 'ಯಾವುದೇ ಮಾಹಿತಿ ಇಲ್ಲ',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    yes: 'ಹೌದು',
    no: 'ಇಲ್ಲ',

    // Dashboard
    welcome: 'ಮರಳಿ ಸ್ವಾಗತ',
    totalRevenue: 'ಒಟ್ಟು ಆದಾಯ',
    totalProducts: 'ಒಟ್ಟು ಉತ್ಪನ್ನಗಳು',
    totalCustomers: 'ಒಟ್ಟು ರೈತರು',
    avgOrderValue: 'ಸರಾಸರಿ ಆದೇಶ ಮೌಲ್ಯ',
    lowStockAlerts: 'ಕಡಿಮೆ ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆಗಳು',
    creditReminders: 'ಸಾಲದ ನೆನಪೋಲೆಗಳು',
    recentTransactions: 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',

    // Shop
    browseProducts: 'ಗುಣಮಟ್ಟದ ಗೊಬ್ಬರಗಳನ್ನು ನೋಡಿ ಮತ್ತು ಖರೀದಿಸಿ',
    addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
    outOfStock: 'ದಾಸ್ತಾನು ಇಲ್ಲ',
    continueShopping: 'ಖರೀದಿಯನ್ನು ಮುಂದುವರಿಸಿ',

    // Cart
    shoppingCart: 'ಶಾಪಿಂಗ್ ಕಾರ್ಟ್',
    clearCart: 'ಕಾರ್ಟ್ ಖಾಲಿ ಮಾಡಿ',
    placeOrder: 'ಆದೇಶ ನೀಡಿ',
    orderSummary: 'ಆದೇಶ ಸಾರಾಂಶ',
    shipping: 'ಶಿಪ್ಪಿಂಗ್',
    tax: 'ತೆರಿಗೆ',
    total: 'ಒಟ್ಟು',

    // Products
    fertilizerInventory: 'ಗೊಬ್ಬರ ದಾಸ್ತಾನು',
    manageProducts: 'ನಿಮ್ಮ ಕೃಷಿ ಉತ್ಪನ್ನಗಳು ಮತ್ತು ಪೂರೈಕೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    productName: 'ಉತ್ಪನ್ನದ ಹೆಸರು',
    type: 'ವಿಧ',
    price: 'ಬೆಲೆ',
    stock: 'ದಾಸ್ತಾನು',
    supplier: 'ಪೂರೈಕೆದಾರರು',
    description: 'ವಿವರಣೆ',

    // Weather
    weatherInsights: 'ಹವಾಮಾನ ಒಳನೋಟಗಳು',
    currentConditions: 'ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ',
    soilMoisture: 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
    recommendation: 'ಶಿಫಾರಸು',
    dayForecast: '5-ದಿನದ ಮುನ್ಸೂಚನೆ',
    humidity: 'ತೇವಾಂಶ',
    windSpeed: 'ಗಾಳಿಯ ವೇಗ',
    farmingAdvice: 'ಕೃಷಿ ಸಲಹೆ',

    // Weather Widget
    yourFarmArea: 'ನಿಮ್ಮ ಫಾರ್ಮ್ ಪ್ರದೇಶ',
    partlyCloudy: 'ಭಾಗಶಃ ಮೋಡ',
    sunny: 'ಬಿಸಿಲು',
    rainy: 'ಮಳೆ',
    cloudy: 'ಮೋಡ',
    goodConditionsFertilizer: 'ಗೊಬ್ಬರ ಹಾಕಲು ಉತ್ತಮ ಸ್ಥಿತಿ. ಮಣ್ಣಿನ ತೇವಾಂಶ ಉತ್ತಮವಾಗಿದೆ.',
    today: 'ಇಂದು',
    tomorrow: 'ನಾಳೆ',
    day3: 'ದಿನ 3',
    day4: 'ದಿನ 4',
    day5: 'ದಿನ 5',
    failedToLoadWeatherData: 'ಹವಾಮಾನ ಮಾಹಿತಿ ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',

    // Farmer Tips
    farmerTips: 'ರೈತರಿಗೆ ಸಲಹೆಗಳು',
    soilTesting: 'ಮಣ್ಣಿನ ಪರೀಕ್ಷೆಯ ಮಹತ್ವ',
    waterConservation: 'ನೀರು ಸಂರಕ್ಷಣೆ',
    pestManagement: 'ಸಮಗ್ರ ಕೀಟ ನಿರ್ವಹಣೆ',

    // Disease Names and Descriptions
    leafBlight: 'ಎಲೆ ಮುರುಟು ರೋಗ',
    healthyPlant: 'ಆರೋಗ್ಯಕರ ಸಸ್ಯ',
    powderyMildew: 'ಬೂಜು ರೋಗ',
    leafBlightDesc: 'ಎಲೆಗಳ ಮೇಲೆ ಕಂದು ಬಣ್ಣದ ಚುಕ್ಕೆಗಳನ್ನು ಉಂಟುಮಾಡುವ ಶಿಲೀಂಧ್ರ ಸೋಂಕು',
    healthyPlantDesc: 'ಯಾವುದೇ ರೋಗದ ಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    powderyMildewDesc: 'ಎಲೆಗಳು ಮತ್ತು ಕಾಂಡಗಳ ಮೇಲೆ ಬಿಳಿ ಬೂದಿಯಂತಹ ಪದರ',
    leafBlightTreatment: 'ತಾಮ್ರ ಆಧಾರಿತ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ ಮತ್ತು ಗಾಳಿಯ ಸಂಚಾರ ಸುಧಾರಿಸಿ',
    healthyPlantTreatment: 'ಪ್ರಸ್ತುತ ಆರೈಕೆ ಕ್ರಮಗಳನ್ನು ಮುಂದುವರಿಸಿ',
    powderyMildewTreatment: 'ಗಂಧಕ ಆಧಾರಿತ ಶಿಲೀಂಧ್ರನಾಶಕ ಬಳಸಿ ಮತ್ತು ತೇವಾಂಶ ಕಡಿಮೆ ಮಾಡಿ',
    leafBlightPreventive: 'ಸಸ್ಯಗಳ ನಡುವೆ ಸರಿಯಾದ ಅಂತರವನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ ಮತ್ತು ಎಲೆಗಳ ಮೇಲೆ ನೀರು ಹಾಕಬೇಡಿ',
    healthyPlantPreventive: 'ನಿಯಮಿತ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ಸರಿಯಾದ ಪೋಷಣೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ',
    powderyMildewPreventive: 'ಗಾಳಿಯ ಸಂಚಾರ ಸುಧಾರಿಸಿ ಮತ್ತು ಎಲೆಗಳನ್ನು ಒದ್ದೆ ಮಾಡಬೇಡಿ',

    // Fertilizer Calculator
    fertilizerCalculator: 'ಗೊಬ್ಬರ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    selectCropType: 'ಪೈರಿನ ವಿಧವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    chooseCrop: 'ಪೈರನ್ನು ಆಯ್ಕೆ ಮಾಡಿ...',
    landArea: 'ಭೂಪ್ರದೇಶ',
    enterArea: 'ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ',
    unit: 'ಘಟಕ',
    acres: 'ಎಕರೆ',
    hectares: 'ಹೆಕ್ಟೇರ್',
    soilType: 'ಮಣ್ಣಿನ ವಿಧ',
    chooseSoilType: 'ಮಣ್ಣಿನ ವಿಧವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ...',
    sandySoil: 'ಮರಳು ಮಣ್ಣು',
    loamySoil: 'ದುಪ್ಪಿ ಮಣ್ಣು',
    claySoil: 'ಜಿಗುಟು ಮಣ್ಣು',
    siltSoil: 'ಹೂಳು ಮಣ್ಣು',
    currentSoilNPKLevels: 'ಪ್ರಸ್ತುತ ಮಣ್ಣಿನ NPK ಮಟ್ಟಗಳು (kg/ha) - ಐಚ್ಛಿಕ',
    calculateFertilizerRequirements: 'ಗೊಬ್ಬರದ ಅಗತ್ಯತೆಗಳನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    fertilizerRecommendations: 'ಗೊಬ್ಬರದ ಶಿಫಾರಸುಗಳು',
    area: 'ಪ್ರದೇಶ',
    requiredNPK: 'ಅಗತ್ಯವಿರುವ NPK',
    recommendedFertilizers: 'ಶಿಫಾರಸು ಮಾಡಲಾದ ಗೊಬ್ಬರಗಳು',
    bags: 'ಚೀಲಗಳು',
    calculateAgain: 'ಮತ್ತೆ ಲೆಕ್ಕಹಾಕಿ',
    calculatorNote: '💡 ಈ ಶಿಫಾರಸುಗಳು ಅಂದಾಜು ಮಾಹಿತಿ. ನಿಖರವಾದ ಅಗತ್ಯತೆಗಳಿಗಾಗಿ ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ ಮತ್ತು ಸ್ಥಳೀಯ ಕೃಷಿ ತಜ್ಞರ ಸಲಹೆಯನ್ನು ಪಡೆಯಿರಿ.',

    // Education Hub
    farmerEducationHub: 'ರೈತ ಶಿಕ್ಷಣ ಕೇಂದ್ರ',
    searchEducationalContent: 'ಶೈಕ್ಷಣಿಕ ವಿಷಯವನ್ನು ಹುಡುಕಿ...',
    educationAllTopics: 'ಎಲ್ಲಾ ವಿಷಯಗಳು',
    soilManagement: 'ಮಣ್ಣಿನ ನಿರ್ವಹಣೆ',
    irrigation: 'ನೀರಾವರಿ',
    pestControl: 'ಕೀಟ ನಿಯಂತ್ರಣ',
    organicFarming: 'ಸಾವಯವ ಕೃಷಿ',
    agriTech: 'ಅಗ್ರಿ-ಟೆಕ್',
    farmBusiness: 'ಫಾರ್ಮ್ ಬಿಸಿನೆಸ್',
    videos: 'ವಿಡಿಯೋಗಳು',
    articles: 'ಲೇಖನಗಳು',
    noContentFound: 'ಯಾವುದೇ ವಿಷಯ ಕಂಡುಬಂದಿಲ್ಲ',
    educationAdjustSearchFilter: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್ ಮಾನದಂಡಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.',

    // Community Forum
    communityForum: 'ಸಮುದಾಯ ವೇದಿಕೆ',
    newPost: 'ಹೊಸ ಪೋಸ್ಟ್',
    shareFarmingExperience: 'ನಿಮ್ಮ ಕೃಷಿ ಅನುಭವವನ್ನು ಹಂಚಿಕೊಳ್ಳಿ ಅಥವಾ ಸಲಹೆ ಕೇಳಿ...',
    post: 'ಪೋಸ್ಟ್ ಮಾಡಿ',
    searchDiscussions: 'ಚರ್ಚೆಗಳನ್ನು ಹುಡುಕಿ...',
    forumAllTopics: 'ಎಲ್ಲಾ ವಿಷಯಗಳು',
    cropDiscussion: 'ಬೆಳೆ ಚರ್ಚೆ',
    pestProblems: 'ಕೀಟ ಸಮಸ್ಯೆಗಳು',
    equipment: 'ಉಪಕರಣಗಳು',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    forumFarmingAdvice: 'ಕೃಷಿ ಸಲಹೆ',
    noDiscussionsFound: 'ಯಾವುದೇ ಚರ್ಚೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    forumAdjustSearchFilter: 'ನಿಮ್ಮ ಹುಡುಕಾಟ ಅಥವಾ ಫಿಲ್ಟರ್ ಮಾನದಂಡಗಳನ್ನು ಸರಿಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.',

    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  },
  mr: {
    // Navigation
    dashboard: 'डॅशबोर्ड',
    shop: 'दुकान',
    cart: 'कार्ट',
    orders: 'ऑर्डर',
    products: 'उत्पादने',
    sales: 'विक्री',
    customers: 'शेतकरी',
    purchases: 'पुरवठादार',
    payments: 'पेमेंट',
    accounting: 'लेखांकन',
    'stock-alerts': 'स्टॉक अलर्ट',
    'mobile-app': 'मोबाईल ॲप',
    analytics: 'विश्लेषण',
    reports: 'अहवाल',
    logout: 'लॉगआउट',
    farmers: 'शेतकरी',
    survey: 'सर्वेक्षण',
    smartAssistantNav: 'स्मार्ट असिस्टंट',
    govtSchemesNav: 'सरकारी योजना',

    // Common
    search: 'शोधा',
    filter: 'फिल्टर',
    add: 'जोडा',
    edit: 'संपादित करा',
    delete: 'हटवा',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    loading: 'लोड होत आहे...',
    noData: 'काहीही माहिती उपलब्ध नाही',
    confirm: 'पुष्टी करा',
    yes: 'हो',
    no: 'नाही',

    // Dashboard
    welcome: 'पुन्हा स्वागत आहे',
    totalRevenue: 'एकूण महसूल',
    totalProducts: 'एकूण उत्पादने',
    totalCustomers: 'एकूण शेतकरी',
    avgOrderValue: 'सरासरी ऑर्डर मूल्य',
    lowStockAlerts: 'कमी स्टॉक अलर्ट',
    creditReminders: 'उधारीची आठवण',
    recentTransactions: 'नुकतेच झालेले व्यवहार',

    // Shop
    browseProducts: 'दर्जेदार खते पहा आणि खरेदी करा',
    addToCart: 'कार्टमध्ये जोडा',
    outOfStock: 'स्टॉक संपला',
    continueShopping: 'खरेदी सुरू ठेवा',

    // Cart
    shoppingCart: 'शॉपिंग कार्ट',
    clearCart: 'कार्ट रिकामे करा',
    placeOrder: 'ऑर्डर द्या',
    orderSummary: 'ऑर्डरचा सारांश',
    shipping: 'शिपिंग',
    tax: 'कर',
    total: 'एकूण',

    // Products
    fertilizerInventory: 'खतांचा साठा',
    manageProducts: 'आपली कृषी उत्पादने आणि पुरवठा व्यवस्थापित करा',
    addProduct: 'उत्पादन जोडा',
    productName: 'उत्पादनाचे नाव',
    type: 'प्रकार',
    price: 'किंमत',
    stock: 'साठा',
    supplier: 'पुरवठादार',
    description: 'वर्णन',

    // Weather
    weatherInsights: 'हवामान माहिती',
    currentConditions: 'सध्याची स्थिती',
    soilMoisture: 'जमिनीतील ओलावा',
    recommendation: 'शिफारस',
    dayForecast: '५-दिवसांचा अंदाज',
    humidity: 'आद्रता',
    windSpeed: 'वारा वेग',
    farmingAdvice: 'शेती सल्ला',

    // Weather Widget
    yourFarmArea: 'तुमचा शेती परिसर',
    partlyCloudy: 'अंशतः ढगाळ',
    sunny: 'सूर्यप्रकाश',
    rainy: 'पाऊस',
    cloudy: 'ढगाळ',
    goodConditionsFertilizer: 'खत देण्यासाठी चांगली हवामान स्थिती. जमिनीतील ओलावा उत्तम आहे.',
    today: 'आज',
    tomorrow: 'उद्या',
    day3: 'दिवस ३',
    day4: 'दिवस ४',
    day5: 'दिवस ५',
    failedToLoadWeatherData: 'हवामान डेटा लोड करण्यात अयशस्वी',

    // Farmer Tips
    farmerTips: 'शेतकऱ्यांसाठी टिप्स आणि सल्ला',
    soilTesting: 'माती परीक्षणाचे महत्त्व',
    waterConservation: 'पाणी बचत',
    pestManagement: 'एकीकृत कीड व्यवस्थापन',

    // Disease Names and Descriptions
    leafBlight: 'पानावरील करपा',
    healthyPlant: 'निरोगी रोप',
    powderyMildew: 'भुईमुगावरील भुरी',
    leafBlightDesc: 'पानांवर तपकिरी ठिपके निर्माण करणारी बुरशीजन्य लागण',
    healthyPlantDesc: 'कोणत्याही रोगाची चिन्हे आढळली नाहीत',
    powderyMildewDesc: 'पानांवर आणि खोडावर पांढरा पिठासारखा थर',
    leafBlightTreatment: 'तांबे-आधारित बुरशीनाशकाचा वापर करा आणि हवा खेळती ठेवा',
    healthyPlantTreatment: 'सध्याची काळजी घेण्याची पद्धत सुरू ठेवा',
    powderyMildewTreatment: 'गंधक-आधारित बुरशीनाशकाचा वापर करा आणि आद्रता कमी करा',
    leafBlightPreventive: 'रोपांमध्ये योग्य अंतर ठेवा आणि वरून पाणी देणे टाळा',
    healthyPlantPreventive: 'नियमित देखरेख आणि योग्य पोषण द्या',
    powderyMildewPreventive: 'हवा खेळती ठेवा आणि पाने ओले करणे टाळा',

    // Fertilizer Calculator
    fertilizerCalculator: 'खत कॅल्क्युलेटर',
    selectCropType: 'पिकाचा प्रकार निवडा',
    chooseCrop: 'पीक निवडा...',
    landArea: 'शेत क्षेत्र',
    enterArea: 'क्षेत्र प्रविष्ट करा',
    unit: 'एकक',
    acres: 'एकर',
    hectares: 'हेक्टर',
    soilType: 'मातीचा प्रकार',
    chooseSoilType: 'मातीचा प्रकार निवडा...',
    sandySoil: 'वाळूमय माती',
    loamySoil: 'दौमत माती',
    claySoil: 'चिकन माती',
    siltSoil: 'गाळाची माती',
    currentSoilNPKLevels: 'सध्याची मातीची NPK पातळी (kg/ha) - पर्यायी',
    calculateFertilizerRequirements: 'खताची गरज मोजा',
    fertilizerRecommendations: 'खताची शिफारस',
    area: 'क्षेत्र',
    requiredNPK: 'आवश्यक NPK',
    recommendedFertilizers: 'शिफारस केलेली खते',
    bags: 'पिशव्या',
    calculateAgain: 'पुन्हा मोजा',
    calculatorNote: '💡 या शिफारसी अंदाजित आहेत. अचूक माहितीसाठी माती परीक्षण आणि स्थानिक तज्ज्ञांचा सल्ला घ्या.',

    // Education Hub
    farmerEducationHub: 'शेतकरी शिक्षण केंद्र',
    searchEducationalContent: 'शैक्षणिक माहिती शोधा...',
    educationAllTopics: 'सर्व विषय',
    soilManagement: 'माती व्यवस्थापन',
    irrigation: 'सिंचन',
    pestControl: 'कीड नियंत्रण',
    organicFarming: 'सेंद्रिय शेती',
    agriTech: 'ॲग्री-टेक',
    farmBusiness: 'शेती व्यवसाय',
    videos: 'व्हिडिओ',
    articles: 'लेख',
    noContentFound: 'काहीही माहिती आढळली नाही',
    educationAdjustSearchFilter: 'तुमचा शोध किंवा फिल्टर बदलण्याचा प्रयत्न करा.',

    // Community Forum
    communityForum: 'सामुदायिक मंच',
    newPost: 'नवीन पोस्ट',
    shareFarmingExperience: 'तुमचा शेतीचा अनुभव सामायिक करा किंवा सल्ला विचारा...',
    post: 'पोस्ट करा',
    searchDiscussions: 'चर्चांमध्ये शोधा...',
    forumAllTopics: 'सर्व विषय',
    cropDiscussion: 'पीक चर्चा',
    pestProblems: 'कीड समस्या',
    equipment: 'साधने',
    marketPrices: 'बाजार भाव',
    forumFarmingAdvice: 'शेती सल्ला',
    noDiscussionsFound: 'काहीही चर्चा आढळली नाही',
    forumAdjustSearchFilter: 'तुमचा शोध किंवा फिल्टर बदलण्याचा प्रयत्न करा.',

    selectLanguage: 'भाषा निवडा',
    english: 'English',
    hindi: 'हिंदी',
    telugu: 'తెలుగు',
    tamil: 'தமிழ்',
    kannada: 'ಕನ್ನಡ',
    marathi: 'मराठी',
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language')
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage)
    }
  }, [])

  const changeLanguage = (newLanguage) => {
    if (translations[newLanguage]) {
      setLanguage(newLanguage)
      localStorage.setItem('language', newLanguage)
    }
  }

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}